version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/api-sever
hooks:
#  ApplicationStop:
#  DownloadBundle:
#  BeforeInstall:
#  Install:
  AfterInstall:
    - location: scripts/aplication_after.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
#  ValidateService:
